version: '3.8'

services:
  # SRS 流媒体服务器
  srs:
    image: ossrs/srs:5
    container_name: cinema-srs
    ports:
      - "1935:1935"     # RTMP 推流端口
      - "1985:1985"     # HTTP API 端口
      - "8080:8080"     # HTTP-FLV/HLS 拉流端口
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
      - ./srs-data:/usr/local/srs/objs/nginx/html
    restart: unless-stopped
    command: ./objs/srs -c conf/srs.conf
    networks:
      - cinema-network

  # Node.js 聊天服务器
  chat-server:
    build: .
    container_name: cinema-chat
    ports:
      - "3000:3000"     # Web 服务端口
    environment:
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - srs
    restart: unless-stopped
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge

volumes:
  srs-data:

